Implemented Multi-Language Support with Internationalization (l10n)
OWASP/BLT-Flutter pull request #349
Opened 2024-02-09 13:47 UTC by Dante291

Added support for languages: 

Espanol
German
French
Hindi
Portuguese
Japanese
Chinese

https://github.com/OWASP/BLT-Flutter/assets/103507835/5139b451-928c-4404-8039-b64b16adc50e

2024-02-09 15:26 UTC, Dante291 commented
@just-ary27 @DonnieBLT please review

2024-02-15 06:51 UTC, DonnieBLT requested changes
From a preliminary review, I have a few tweaks 1) would be can you please alphabetize the entries? I had some feedback for a few of the translations and 2) I will do a secondary review after these first changes are made. 3) please use the word Issue / issues and avoid the word problem / problems. This PR looks great. I'm very excited to get it merged in. Thank you so much for this work.

2024-02-15 06:51 UTC, DonnieBLT commented on lib/l10n/app_de.arb
here are the corrections and clarifications for the provided translations:

1. **"rememberMe"**: Should be translated as "Angemeldet bleiben" instead of "Erinnere dich," to reflect the common usage in login contexts, meaning "Stay logged in."

2. **"emailUpdatePasswordInfo"**: A smoother translation could be: "Nach Eingabe Ihrer E-Mail-Adresse erhalten Sie eine E-Mail zum Zurücksetzen des Passworts. Dies ist nur für Konten verfügbar, die mit einem Benutzernamen und Passwort erstellt wurden," to enhance clarity and flow.

3. **"whatsInItForYou"**: Depending on context, "Was hast du davon?" might be more natural and engaging.

4. **"howItWorks"**: If it's intended as a question, it should be "Wie funktioniert es?". If it's a statement, a more natural translation could be "So funktioniert's."

All other translations were accurate and required no changes based on the provided list.

For the context of a GitHub issue or similar platform, where "issue" refers to a bug, feature request, or other points for discussion, a suitable German word is "Problem." However, for a more specific context, like software development or technical discussions, "Issue" is also commonly used in German, especially in professional or technical environments, as it precisely captures the concept of issue tracking systems.

Let's use Issue

2024-02-15 06:51 UTC, DonnieBLT commented on lib/l10n/app_es.arb
> +  "title":"Title"
"title": You've provided the English word "Title" at the end of the list. The correct Spanish translation would be "Título".

2024-02-15 19:30 UTC, Dante291 commented
@DonnieBLT Sir I have made required changes also I haven't arranged translation files in alphabetical order because we could arrange them later when we wont have to add translations in the App, for now this is ready for second review.

2024-02-17 19:07 UTC, DonnieBLT approved these changes

2024-02-17 19:12 UTC, merged